// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Qsjd8T7XHouyWTqMddil4wn1yzFIxYg',
    appId: '1:430270320192:web:d57d66902198762ee499a5',
    messagingSenderId: '430270320192',
    projectId: 'travelll-45e89',
    authDomain: 'travelll-45e89.firebaseapp.com',
    storageBucket: 'travelll-45e89.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrZOdSX8ar4YAcAAsSHdTvaA6pdgYAgfM',
    appId: '1:430270320192:android:0698a1ff1eee4e8de499a5',
    messagingSenderId: '430270320192',
    projectId: 'travelll-45e89',
    storageBucket: 'travelll-45e89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc_T6GXMZZBAk--HM5H4Uxs0on4V70zOk',
    appId: '1:430270320192:ios:99c55012c559bf17e499a5',
    messagingSenderId: '430270320192',
    projectId: 'travelll-45e89',
    storageBucket: 'travelll-45e89.firebasestorage.app',
    iosBundleId: 'com.etravel.eTravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc_T6GXMZZBAk--HM5H4Uxs0on4V70zOk',
    appId: '1:430270320192:ios:99c55012c559bf17e499a5',
    messagingSenderId: '430270320192',
    projectId: 'travelll-45e89',
    storageBucket: 'travelll-45e89.firebasestorage.app',
    iosBundleId: 'com.etravel.eTravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1Qsjd8T7XHouyWTqMddil4wn1yzFIxYg',
    appId: '1:430270320192:web:28739b196d8b10a8e499a5',
    messagingSenderId: '430270320192',
    projectId: 'travelll-45e89',
    authDomain: 'travelll-45e89.firebaseapp.com',
    storageBucket: 'travelll-45e89.firebasestorage.app',
  );
}